# Generated by Django 4.2.1 on 2023-05-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenditure",
            name="money",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="income", name="money", field=models.IntegerField(default=0),
        ),
    ]
